### ISSUE TITLE
$ gem install laser # don't work!

### ISSUE THREAD

**Issue by linuxonrails** [michaeledgar/laser#1]
$ gem install laser # don't work!
ERROR:  Could not find a valid gem 'laser' (>= 0) in any repository

**Comment by marcoow** [comment]
when do you plan to actually release the gem? would be very interested...

**Comment by agrimm** [comment]
All I want is frickin' Ruby with frickin' laser beams! You said in the documentation that it's possible to do gem install laser! :(

Workaround: download a local copy, them build the gem and install it.

**Comment by michaeledgar** [comment]
Sorry for not having an actual gem out - I'm hoping to push one soon, but it's hard to demonstrate what the binary does other than suck CPU cycles at this point.

**Comment by michaeledgar** [comment]
The first prerelease version is out! `gem install laser --prerelease` will do the trick. Compilation of a smal C++ extension may fail on Windows.

**Comment by marcoow** [comment]
nice!
