### ISSUE TITLE
Ripper problems on 1.8

### ISSUE THREAD

**Issue by agrimm** [michaeledgar/laser#19]
Laser 0.7.0.pre2 has problems with regards to Ripper on Ruby 1.8.

With a fresh install:

agrimm@proline:~$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
agrimm@proline:~$ ruby -S laser --version
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- ripper (LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/laser-0.7.0.pre2/bin/../lib/laser.rb:25
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`require'
    from /var/lib/gems/1.8/gems/laser-0.7.0.pre2/bin/laser:6
    from /usr/local/bin/laser:19:in `load'
    from /usr/local/bin/laser:19

Then once ripper is installed:

agrimm@proline:~$ ruby -S laser --version
/var/lib/gems/1.8/gems/ripper-plus-1.3.0/lib/ripper-plus.rb:2: ripper-plus requires Ruby 1.9+ (RuntimeError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`polyglot_original_require'
    from /var/lib/gems/1.8/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
    from /var/lib/gems/1.8/gems/laser-0.7.0.pre2/bin/../lib/laser.rb:27
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/laser-0.7.0.pre2/bin/laser:6
    from /usr/local/bin/laser:19:in`load'
    from /usr/local/bin/laser:19

Don't know if this is the case on trunk.

**Comment by egonSchiele** [comment]
This would seem to indicate that ruby 1.9 is required:

> /var/lib/gems/1.8/gems/ripper-plus-1.3.0/lib/ripper-plus.rb ripper-plus requires Ruby 1.9+ (RuntimeError)

**Comment by agrimm** [comment]
The `ripper-plus requires Ruby 1.9+` error mentioned by @egonSchiele exists on the trunk version of laser, as well as 0.7.0.pre2.

**Comment by dgutov** [comment]
Have you seen the README?

```
Ruby 1.9+ only - Yep, LASER will only run on Ruby 1.9, and it'll expect its target code is Ruby 1.9.
```
